apiVersion: v1
kind: ConfigMap
metadata:
  name: django-vue-adminx-config
  namespace: django-vue-adminx
data:
  DEBUG: "False"
  DB_NAME: "django_vue_adminx"
  DB_USER: "django"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DATABASE_URL: "mysql://django:django123@mysql-service:3306/django_vue_adminx"

