apiVersion: v1
kind: Secret
metadata:
  name: django-vue-adminx-secret
  namespace: django-vue-adminx
type: Opaque
stringData:
  SECRET_KEY: "django-insecure--mpclg7e91pkc&c+dz3lcf%=ddfye@9asvaf4z7xnjd9tpt#bb"
  DB_PASSWORD: "django123"
  MYSQL_ROOT_PASSWORD: "root123"

